name: all-checks

on:
  workflow_run:
    workflows:
      - rust-bench
      - rust-lint
      - rust-test
    types:
      - completed

jobs:
  check:
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Aggregate results
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(github.event.workflow_run) }}
